//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.1
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProject.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TestProject.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;ID xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; descr=&quot;kjv&quot; alphabet=&quot;ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz&quot;&gt;
        ///  &lt;BOOK bnumber=&quot;1&quot; bshort=&quot;ge;gen;gn;genesis&quot;&gt;Genesis&lt;/BOOK&gt;
        ///  &lt;BOOK bnumber=&quot;2&quot; bshort=&quot;ex;exo;exod;exodus&quot;&gt;Exodus&lt;/BOOK&gt;
        ///  &lt;BOOK bnumber=&quot;3&quot; bshort=&quot;lev;le;lv;levit;leviticus&quot;&gt;Leviticus&lt;/BOOK&gt;
        ///  &lt;BOOK bnumber=&quot;4&quot; bshort=&quot;nu;num;nm;numb;numbers&quot;&gt;Numbers&lt;/BOOK&gt;
        ///  &lt;BOOK bnumber=&quot;5&quot; bshort=&quot;de;deut;deu;d [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string BibleBooskInfo_kjv {
            get {
                return ResourceManager.GetString("BibleBooskInfo_kjv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;ID descr=&quot;rst&quot; alphabet=&quot;АБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯабвгдеёжзийклмнопрстуфхцчшщъыьэюя&quot;&gt;
        ///  &lt;BOOK bnumber=&quot;1&quot; bshort=&quot;быт;бт;бытие&quot;&gt;Бытие&lt;/BOOK&gt;
        ///  &lt;BOOK bnumber=&quot;2&quot; bshort=&quot;исх;исход&quot;&gt;Исход&lt;/BOOK&gt;
        ///  &lt;BOOK bnumber=&quot;3&quot; bshort=&quot;лев;лв;левит&quot;&gt;Левит&lt;/BOOK&gt;
        ///  &lt;BOOK bnumber=&quot;4&quot; bshort=&quot;чис;чс;числ;числа&quot;&gt;Числа&lt;/BOOK&gt;
        ///  &lt;BOOK bnumber=&quot;5&quot; bshort=&quot;втор;вт;втрзк;второзаконие&quot;&gt;Второзаконие&lt;/BOOK&gt;
        ///  &lt;BOOK bnumber=&quot;6&quot; bshort=&quot;нав;иисус;навин&quot;&gt;Иисус Навин&lt;/BOOK&gt;
        ///  &lt;BOOK bnumber=&quot;7&quot; bshor [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string BibleBooskInfo_rst {
            get {
                return ResourceManager.GetString("BibleBooskInfo_rst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;BibleTranslationDifferences xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; PartVersesAlphabet=&quot;абвгд&quot;&gt;
        ///  &lt;BookDifferences BookIndex=&quot;3&quot;&gt;
        ///    &lt;Difference BaseVerses=&quot;14:55-56&quot; ParallelVerses=&quot;14:55&quot; /&gt;
        ///    &lt;Difference BaseVerses=&quot;14:57&quot; ParallelVerses=&quot;14:56&quot; /&gt;
        ///  &lt;/BookDifferences&gt;
        ///  &lt;BookDifferences BookIndex=&quot;4&quot;&gt;
        ///    &lt;Difference BaseVerses=&quot;12:16&quot; ParallelVerses=&quot;13:1&quot; /&gt;
        ///    &lt;Difference BaseVerses=&quot;13:1-33&quot; ParallelVerses= [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string rst {
            get {
                return ResourceManager.GetString("rst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;BibleTranslationDifferences xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; PartVersesAlphabet=&quot;абвгд&quot;&gt;
        ///  &lt;BookDifferences BookIndex=&quot;3&quot;&gt;
        ///    &lt;Difference BaseVerses=&quot;14:55-56&quot; ParallelVerses=&quot;14:55&quot; /&gt;
        ///    &lt;Difference BaseVerses=&quot;14:57&quot; ParallelVerses=&quot;14:56&quot; /&gt;
        ///  &lt;/BookDifferences&gt;
        ///  &lt;BookDifferences BookIndex=&quot;4&quot;&gt;
        ///    &lt;Difference BaseVerses=&quot;12:16&quot; ParallelVerses=&quot;13:1&quot; /&gt;
        ///    &lt;Difference BaseVerses=&quot;13:1-3 [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string rst77 {
            get {
                return ResourceManager.GetString("rst77", resourceCulture);
            }
        }
    }
}
