//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BibleCommon.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Constants {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Constants() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BibleCommon.Resources.Constants", typeof(Constants).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string _LANGUAGE_NAME {
            get {
                return ResourceManager.GetString("_LANGUAGE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding parallel Bible translation start.
        /// </summary>
        public static string AddParallelBibleTranslation {
            get {
                return ResourceManager.GetString("AddParallelBibleTranslation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parallel Bible translation was added successfully.
        /// </summary>
        public static string AddParallelBibleTranslationFinishMessage {
            get {
                return ResourceManager.GetString("AddParallelBibleTranslationFinishMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new module.
        /// </summary>
        public static string AddSupplementalModule {
            get {
                return ResourceManager.GetString("AddSupplementalModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sasha &amp; Natasha.
        /// </summary>
        public static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup created successfully..
        /// </summary>
        public static string BackupManagerFinishMessage {
            get {
                return ResourceManager.GetString("BackupManagerFinishMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup of notebook &apos;{0}&apos; created successfully..
        /// </summary>
        public static string BackupManagerNotebookCompleted {
            get {
                return ResourceManager.GetString("BackupManagerNotebookCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packaging to .zip archive..
        /// </summary>
        public static string BackupManagerToZipArchive {
            get {
                return ResourceManager.GetString("BackupManagerToZipArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup starts.
        /// </summary>
        public static string BackupStartInfo {
            get {
                return ResourceManager.GetString("BackupStartInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The passage can not be found.
        /// </summary>
        public static string BibleVersePointerCanNotFindPlace {
            get {
                return ResourceManager.GetString("BibleVersePointerCanNotFindPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String cannot be parsed.
        /// </summary>
        public static string BibleVersePointerCanNotParseString {
            get {
                return ResourceManager.GetString("BibleVersePointerCanNotParseString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify the Bible verse.
        /// </summary>
        public static string BibleVersePointerDescription {
            get {
                return ResourceManager.GetString("BibleVersePointerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open a verse.
        /// </summary>
        public static string BibleVersePointerTitle {
            get {
                return ResourceManager.GetString("BibleVersePointerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to books.
        /// </summary>
        public static string Books {
            get {
                return ResourceManager.GetString("Books", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This module contains another text of the Bible and other versions of abbreviations of books. For correct program work    the follow notebooks must be re-created: Bible, Comments to the Bible, Summary of Notes. Continue?.
        /// </summary>
        public static string ChangeModuleWarning {
            get {
                return ResourceManager.GetString("ChangeModuleWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OneNote notebooks request fails. Please retry..
        /// </summary>
        public static string ConfiguratorCanNotRequestDataFromOneNote {
            get {
                return ResourceManager.GetString("ConfiguratorCanNotRequestDataFromOneNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notebook open error.
        /// </summary>
        public static string ConfiguratorErrorWhileNotebookOpenning {
            get {
                return ResourceManager.GetString("ConfiguratorErrorWhileNotebookOpenning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating notebook.
        /// </summary>
        public static string ConfiguratorNotebookCreation {
            get {
                return ResourceManager.GetString("ConfiguratorNotebookCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notebook not defined.
        /// </summary>
        public static string ConfiguratorNotebookNotDefined {
            get {
                return ResourceManager.GetString("ConfiguratorNotebookNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notebook template not found at.
        /// </summary>
        public static string ConfiguratorNotebookTemplateNotFound {
            get {
                return ResourceManager.GetString("ConfiguratorNotebookTemplateNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete all summary of notes and references to them?.
        /// </summary>
        public static string ConfiguratorQuestionDeleteAllNotesPages {
            get {
                return ResourceManager.GetString("ConfiguratorQuestionDeleteAllNotesPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Summary of Notes&apos; pages use a separate notebook. It is recommended to manually remove the notebook &apos;Summary of Notes&apos; and recreate it from template. Continue?.
        /// </summary>
        public static string ConfiguratorQuestionDeleteAllNotesPagesManually {
            get {
                return ResourceManager.GetString("ConfiguratorQuestionDeleteAllNotesPagesManually", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section group not found.
        /// </summary>
        public static string ConfiguratorSectionGroupNotFound {
            get {
                return ResourceManager.GetString("ConfiguratorSectionGroupNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create the notebook. Select a different folder..
        /// </summary>
        public static string ConfiguratorSelectAnotherFolder {
            get {
                return ResourceManager.GetString("ConfiguratorSelectAnotherFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify notebook location.
        /// </summary>
        public static string ConfiguratorSetNotebookFolder {
            get {
                return ResourceManager.GetString("ConfiguratorSetNotebookFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong notebook specified &apos;{0}&apos; for type &apos;{1}&apos;..
        /// </summary>
        public static string ConfiguratorWrongNotebookSelected {
            get {
                return ResourceManager.GetString("ConfiguratorWrongNotebookSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong parameter value.
        /// </summary>
        public static string ConfiguratorWrongParameterValue {
            get {
                return ResourceManager.GetString("ConfiguratorWrongParameterValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating Supplemental Bible start.
        /// </summary>
        public static string CreateSupplementalBible {
            get {
                return ResourceManager.GetString("CreateSupplementalBible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplemental Bible was created successfully.
        /// </summary>
        public static string CreateSupplementalBibleFinishMessage {
            get {
                return ResourceManager.GetString("CreateSupplementalBibleFinishMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Module is undefined..
        /// </summary>
        public static string CurrentModuleIsUndefined {
            get {
                return ResourceManager.GetString("CurrentModuleIsUndefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string DefaultPageName_Notes {
            get {
                return ResourceManager.GetString("DefaultPageName_Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detailed notes.
        /// </summary>
        public static string DefaultPageName_RubbishNotes {
            get {
                return ResourceManager.GetString("DefaultPageName_RubbishNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview.
        /// </summary>
        public static string DefaultPageNameDefaultBookOverview {
            get {
                return ResourceManager.GetString("DefaultPageNameDefaultBookOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string DefaultPageNameDefaultComments {
            get {
                return ResourceManager.GetString("DefaultPageNameDefaultComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify notebook folder.
        /// </summary>
        public static string DefineNotebookDirectory {
            get {
                return ResourceManager.GetString("DefineNotebookDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Summary of Notes&apos; pages deleting completed successfully..
        /// </summary>
        public static string DeleteNotesPagesManagerFinishMessage {
            get {
                return ResourceManager.GetString("DeleteNotesPagesManagerFinishMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page deleting.
        /// </summary>
        public static string DeleteNotesPagesManagerRemovePage {
            get {
                return ResourceManager.GetString("DeleteNotesPagesManagerRemovePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Summary of Notes&apos; pages deleting start..
        /// </summary>
        public static string DeleteNotesPagesManagerStartMessage {
            get {
                return ResourceManager.GetString("DeleteNotesPagesManagerStartMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close the Supplemental Bible Notebook?.
        /// </summary>
        public static string DeleteSupplementalBibleQuestion {
            get {
                return ResourceManager.GetString("DeleteSupplementalBibleQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove this module.
        /// </summary>
        public static string DeleteThisModule {
            get {
                return ResourceManager.GetString("DeleteThisModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove this module?.
        /// </summary>
        public static string DeleteThisModuleQuestion {
            get {
                return ResourceManager.GetString("DeleteThisModuleQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://IStudyBibleTools.com/download.htm?fromProgram=true.
        /// </summary>
        public static string DownloadPageUrl {
            get {
                return ResourceManager.GetString("DownloadPageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not find a hierarchy of type &apos;{0}&apos; for element &apos;{1}&apos; {2}.
        /// </summary>
        public static string Error_CanNotFindHierarchy {
            get {
                return ResourceManager.GetString("Error_CanNotFindHierarchy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid module:.
        /// </summary>
        public static string Error_InvalidModule {
            get {
                return ResourceManager.GetString("Error_InvalidModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notebook template not specified for type &apos;{0}&apos;..
        /// </summary>
        public static string Error_NotebookTemplateNotDefined {
            get {
                return ResourceManager.GetString("Error_NotebookTemplateNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notebook template not found: &apos;{0}&apos; of type &apos;{1}&apos;..
        /// </summary>
        public static string Error_NotebookTemplateNotFound {
            get {
                return ResourceManager.GetString("Error_NotebookTemplateNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opened notebook not found.
        /// </summary>
        public static string Error_OpenedNotebookNotFound {
            get {
                return ResourceManager.GetString("Error_OpenedNotebookNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opened notes page not found.
        /// </summary>
        public static string Error_OpenedNotePageNotFound {
            get {
                return ResourceManager.GetString("Error_OpenedNotePageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section group of type &apos;{0}&apos; not specified in notebook template of type &apos;{1}&apos;..
        /// </summary>
        public static string Error_SectionGroupNotDefined {
            get {
                return ResourceManager.GetString("Error_SectionGroupNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The program is not configured. Open the &apos;Program parameters&apos; and specify the necessary settings..
        /// </summary>
        public static string Error_SystemIsNotConfigures {
            get {
                return ResourceManager.GetString("Error_SystemIsNotConfigures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to update the page. Perhaps on the page there are painted with a brush elements, which are currently not supported. \nDelete  this elements and try again..
        /// </summary>
        public static string Error_UpdateError_InksOnPages {
            get {
                return ResourceManager.GetString("Error_UpdateError_InksOnPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update page error.
        /// </summary>
        public static string Error_UpdatePage {
            get {
                return ResourceManager.GetString("Error_UpdatePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred.
        /// </summary>
        public static string ErrorOccurred {
            get {
                return ResourceManager.GetString("ErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR.
        /// </summary>
        public static string ErrorUpper {
            get {
                return ResourceManager.GetString("ErrorUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &apos;{0}&apos; not found..
        /// </summary>
        public static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully completed..
        /// </summary>
        public static string FinishSuccessfully {
            get {
                return ResourceManager.GetString("FinishSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed with errors..
        /// </summary>
        public static string FinishWithErrors {
            get {
                return ResourceManager.GetString("FinishWithErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linking Supplemental Bible start.
        /// </summary>
        public static string LinkSupplementalBible {
            get {
                return ResourceManager.GetString("LinkSupplementalBible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplimental Bible was linked successfully.
        /// </summary>
        public static string LinkSupplementalBibleFinishMessage {
            get {
                return ResourceManager.GetString("LinkSupplementalBibleFinishMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To upload the module, use the tab &quot;Modules&quot; of the running application..
        /// </summary>
        public static string LoadMofuleInExistingInstance {
            get {
                return ResourceManager.GetString("LoadMofuleInExistingInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Name.
        /// </summary>
        public static string ModuleDisplayName {
            get {
                return ResourceManager.GetString("ModuleDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information about the module.
        /// </summary>
        public static string ModuleInformation {
            get {
                return ResourceManager.GetString("ModuleInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Active.
        /// </summary>
        public static string ModuleIsActive {
            get {
                return ResourceManager.GetString("ModuleIsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error on module &apos;{0}&apos; loading: {1}.
        /// </summary>
        public static string ModuleUploadError {
            get {
                return ResourceManager.GetString("ModuleUploadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string ModuleVersion {
            get {
                return ResourceManager.GetString("ModuleVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The module with the same name already exists. The current module will be replaced. Continue?.
        /// </summary>
        public static string ModuleWithSameNameAlreadyExists {
            get {
                return ResourceManager.GetString("ModuleWithSameNameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another instance of this program is running..
        /// </summary>
        public static string MoreThanSingleInstanceRun {
            get {
                return ResourceManager.GetString("MoreThanSingleInstanceRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://IStudyBibleTools.com/ServerVariables.xml.
        /// </summary>
        public static string NewVersionOnServerFileUrl {
            get {
                return ResourceManager.GetString("NewVersionOnServerFileUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section group can not be found.
        /// </summary>
        public static string NotebookIteratorCanNotFindSectionGroup {
            get {
                return ResourceManager.GetString("NotebookIteratorCanNotFindSectionGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OneNote hierarchy updating.
        /// </summary>
        public static string NoteLilnkerHierarchyUpdating {
            get {
                return ResourceManager.GetString("NoteLilnkerHierarchyUpdating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort pages error.
        /// </summary>
        public static string NoteLinkerErrorWhilePageSorting {
            get {
                return ResourceManager.GetString("NoteLinkerErrorWhilePageSorting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close the program?.
        /// </summary>
        public static string NoteLinkerFormCaptionOnClosing {
            get {
                return ResourceManager.GetString("NoteLinkerFormCaptionOnClosing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide details.
        /// </summary>
        public static string NoteLinkerHideDetails {
            get {
                return ResourceManager.GetString("NoteLinkerHideDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing....
        /// </summary>
        public static string NoteLinkerInitialization {
            get {
                return ResourceManager.GetString("NoteLinkerInitialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating references to &apos;Summary of Notes&apos; pages.
        /// </summary>
        public static string NoteLinkerLinksToNotesPagesUpdating {
            get {
                return ResourceManager.GetString("NoteLinkerLinksToNotesPagesUpdating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found.
        /// </summary>
        public static string NoteLinkerManyFound {
            get {
                return ResourceManager.GetString("NoteLinkerManyFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pages.
        /// </summary>
        public static string NoteLinkerManyPages {
            get {
                return ResourceManager.GetString("NoteLinkerManyPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No elements selected.
        /// </summary>
        public static string NoteLinkerNoElementSelected {
            get {
                return ResourceManager.GetString("NoteLinkerNoElementSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Summary of Notes&apos; pages updating.
        /// </summary>
        public static string NoteLinkerNotesPagesUpdating {
            get {
                return ResourceManager.GetString("NoteLinkerNotesPagesUpdating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pages.
        /// </summary>
        public static string NoteLinkerOfManyPages {
            get {
                return ResourceManager.GetString("NoteLinkerOfManyPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found.
        /// </summary>
        public static string NoteLinkerOneFound {
            get {
                return ResourceManager.GetString("NoteLinkerOneFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page.
        /// </summary>
        public static string NoteLinkerOnePage {
            get {
                return ResourceManager.GetString("NoteLinkerOnePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OneNote pages updating.
        /// </summary>
        public static string NoteLinkerPagesUpdating {
            get {
                return ResourceManager.GetString("NoteLinkerPagesUpdating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing notebook.
        /// </summary>
        public static string NoteLinkerProcessNotebook {
            get {
                return ResourceManager.GetString("NoteLinkerProcessNotebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In some cases this can lead to incorrect sorting of &apos;Summary of Notes&apos; pages, which is solved only by removing all the &apos;Summary of Notes&apos; pages. Contniue terminating the program?.
        /// </summary>
        public static string NoteLinkerQuestionOnClosing {
            get {
                return ResourceManager.GetString("NoteLinkerQuestionOnClosing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show details.
        /// </summary>
        public static string NoteLinkerShowDetails {
            get {
                return ResourceManager.GetString("NoteLinkerShowDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final chapter processing.
        /// </summary>
        public static string NoteLinkManagerChapterProcessing {
            get {
                return ResourceManager.GetString("NoteLinkManagerChapterProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while processing of the page..
        /// </summary>
        public static string NoteLinkManagerProcessingPageErrors {
            get {
                return ResourceManager.GetString("NoteLinkManagerProcessingPageErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing the &apos;Summary of Notes&apos; page.
        /// </summary>
        public static string NoteLinkManagerProcessNotesPage {
            get {
                return ResourceManager.GetString("NoteLinkManagerProcessNotesPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verse cell not found.
        /// </summary>
        public static string NoteLinkManagerVerseCellNotFound {
            get {
                return ResourceManager.GetString("NoteLinkManagerVerseCellNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process aborted by user.
        /// </summary>
        public static string ProcessAbortedByUser {
            get {
                return ResourceManager.GetString("ProcessAbortedByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing the book.
        /// </summary>
        public static string ProcessBook {
            get {
                return ResourceManager.GetString("ProcessBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing chapter.
        /// </summary>
        public static string ProcessChapter {
            get {
                return ResourceManager.GetString("ProcessChapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current page processing.
        /// </summary>
        public static string ProcessCurrentPage {
            get {
                return ResourceManager.GetString("ProcessCurrentPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notebook processing.
        /// </summary>
        public static string ProcessNotebook {
            get {
                return ResourceManager.GetString("ProcessNotebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing the page.
        /// </summary>
        public static string ProcessPage {
            get {
                return ResourceManager.GetString("ProcessPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing the section.
        /// </summary>
        public static string ProcessSection {
            get {
                return ResourceManager.GetString("ProcessSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing the section group.
        /// </summary>
        public static string ProcessSectionGroup {
            get {
                return ResourceManager.GetString("ProcessSectionGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing the verse.
        /// </summary>
        public static string ProcessVerse {
            get {
                return ResourceManager.GetString("ProcessVerse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to References to Comments to the Bible have been updated..
        /// </summary>
        public static string RelinkBibleCommentsManagerFinishMessage {
            get {
                return ResourceManager.GetString("RelinkBibleCommentsManagerFinishMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start updating references to the Comments to the Bible..
        /// </summary>
        public static string RelinkBibleCommentsManagerStartMessage {
            get {
                return ResourceManager.GetString("RelinkBibleCommentsManagerStartMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing parallel Bible translation start.
        /// </summary>
        public static string RemoveParallelBibleTranslation {
            get {
                return ResourceManager.GetString("RemoveParallelBibleTranslation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parallel Bible translation was removed successfully.
        /// </summary>
        public static string RemoveParallelBibleTranslationFinishMessage {
            get {
                return ResourceManager.GetString("RemoveParallelBibleTranslationFinishMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplemental Bible was closed successfully.
        /// </summary>
        public static string RemoveSupplementalBibleFinishMessage {
            get {
                return ResourceManager.GetString("RemoveSupplementalBibleFinishMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bible pages width have been successfully changed..
        /// </summary>
        public static string ResizeBibleTableManagerFinishMessage {
            get {
                return ResourceManager.GetString("ResizeBibleTableManagerFinishMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start changing the Bible pages width..
        /// </summary>
        public static string ResizeBibleTableManagerStartMessage {
            get {
                return ResourceManager.GetString("ResizeBibleTableManagerStartMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section group &apos;{0}&apos; not found..
        /// </summary>
        public static string SectionGroupNotFound {
            get {
                return ResourceManager.GetString("SectionGroupNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section group of type &apos;{0}&apos; not found..
        /// </summary>
        public static string SectionGroupOfTypeNotFound {
            get {
                return ResourceManager.GetString("SectionGroupOfTypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified Notebook is of type &apos;{0}&apos;..
        /// </summary>
        public static string SelectedNotebookForType {
            get {
                return ResourceManager.GetString("SelectedNotebookForType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select file with the extension &apos;{0}&apos;..
        /// </summary>
        public static string SelectFileWithExtension {
            get {
                return ResourceManager.GetString("SelectFileWithExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locking the Bible stored in SkyDrive is not currently supported. Use another kind of internet storage..
        /// </summary>
        public static string SkyDriveBibleIsNotSupportedForLock {
            get {
                return ResourceManager.GetString("SkyDriveBibleIsNotSupportedForLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stage.
        /// </summary>
        public static string Stage {
            get {
                return ResourceManager.GetString("Stage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start time.
        /// </summary>
        public static string StartTime {
            get {
                return ResourceManager.GetString("StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplemental Bible.
        /// </summary>
        public static string SupplementalBibleName {
            get {
                return ResourceManager.GetString("SupplementalBibleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time spent.
        /// </summary>
        public static string TimeSpent {
            get {
                return ResourceManager.GetString("TimeSpent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this module.
        /// </summary>
        public static string UseThisModule {
            get {
                return ResourceManager.GetString("UseThisModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to verse.
        /// </summary>
        public static string Verse {
            get {
                return ResourceManager.GetString("Verse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OneNote not started.
        /// </summary>
        public static string VerseLinkerOneNoteNotStarted {
            get {
                return ResourceManager.GetString("VerseLinkerOneNoteNotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Underlined text cannot be extracted.
        /// </summary>
        public static string VerseLinkerUnderlineTextNotExtracted {
            get {
                return ResourceManager.GetString("VerseLinkerUnderlineTextNotExtracted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Underline text not found.
        /// </summary>
        public static string VerseLinkerUnderlineTextNotFound {
            get {
                return ResourceManager.GetString("VerseLinkerUnderlineTextNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments page not found.
        /// </summary>
        public static string VerseLinkManagerCommentPageNotFound {
            get {
                return ResourceManager.GetString("VerseLinkManagerCommentPageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments section group not found.
        /// </summary>
        public static string VerseLinkManagerCommentSectionGroupNotFound {
            get {
                return ResourceManager.GetString("VerseLinkManagerCommentSectionGroupNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments section not found.
        /// </summary>
        public static string VerseLinkManagerCommentSectionNotFound {
            get {
                return ResourceManager.GetString("VerseLinkManagerCommentSectionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It most likely that not a Bible page is opened in OneNote..
        /// </summary>
        public static string VerseLinkManagerOpenNotBiblePage {
            get {
                return ResourceManager.GetString("VerseLinkManagerOpenNotBiblePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ; .
        /// </summary>
        public static string VerseLinksDelimiter {
            get {
                return ResourceManager.GetString("VerseLinksDelimiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to link {0}.
        /// </summary>
        public static string VerseLinkTemplate {
            get {
                return ResourceManager.GetString("VerseLinkTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning!.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://IStudyBibleTools.com.
        /// </summary>
        public static string WebSiteUrl {
            get {
                return ResourceManager.GetString("WebSiteUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong quantity of section groups. Expected {0}, found {1}..
        /// </summary>
        public static string WrongSectionGroupsCount {
            get {
                return ResourceManager.GetString("WrongSectionGroupsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong quantity of sections in section group &apos;{0}&apos;. Expected {1}, found {2}..
        /// </summary>
        public static string WrongSectionsCountInSectionGroup {
            get {
                return ResourceManager.GetString("WrongSectionsCountInSectionGroup", resourceCulture);
            }
        }
    }
}
