//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.239
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BibleCommon.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Constants {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Constants() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BibleCommon.Resources.Constants", typeof(Constants).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на English.
        /// </summary>
        public static string _LANGUAGE_NAME {
            get {
                return ResourceManager.GetString("_LANGUAGE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Abort the operation?.
        /// </summary>
        public static string AbortTheOperation {
            get {
                return ResourceManager.GetString("AbortTheOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Dictionary was added successfully.
        /// </summary>
        public static string AddDictionaryFinishMessage {
            get {
                return ResourceManager.GetString("AddDictionaryFinishMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Adding Dictionary start.
        /// </summary>
        public static string AddDictionaryStart {
            get {
                return ResourceManager.GetString("AddDictionaryStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Additional modules.
        /// </summary>
        public static string AdditionalModules {
            get {
                return ResourceManager.GetString("AdditionalModules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Adding parallel Bible translation.
        /// </summary>
        public static string AddParallelBibleTranslation {
            get {
                return ResourceManager.GetString("AddParallelBibleTranslation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Parallel Bible translation was added successfully.
        /// </summary>
        public static string AddParallelBibleTranslationFinishMessage {
            get {
                return ResourceManager.GetString("AddParallelBibleTranslationFinishMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Adding parallel Bible translation start.
        /// </summary>
        public static string AddParallelBibleTranslationStart {
            get {
                return ResourceManager.GetString("AddParallelBibleTranslationStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add new module.
        /// </summary>
        public static string AddSupplementalModule {
            get {
                return ResourceManager.GetString("AddSupplementalModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на All Dictionaries.
        /// </summary>
        public static string AllDictionaries {
            get {
                return ResourceManager.GetString("AllDictionaries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Apply.
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sasha &amp; Natasha.
        /// </summary>
        public static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Backup created successfully..
        /// </summary>
        public static string BackupManagerFinishMessage {
            get {
                return ResourceManager.GetString("BackupManagerFinishMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Backup of notebook &apos;{0}&apos; created successfully..
        /// </summary>
        public static string BackupManagerNotebookCompleted {
            get {
                return ResourceManager.GetString("BackupManagerNotebookCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Packaging to .zip archive..
        /// </summary>
        public static string BackupManagerToZipArchive {
            get {
                return ResourceManager.GetString("BackupManagerToZipArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Backup starts.
        /// </summary>
        public static string BackupStartInfo {
            get {
                return ResourceManager.GetString("BackupStartInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Version of primary Bible module is {0}. Only {1} and greater is supported..
        /// </summary>
        public static string BaseModuleIsNotSupported {
            get {
                return ResourceManager.GetString("BaseModuleIsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Base modules.
        /// </summary>
        public static string BaseModules {
            get {
                return ResourceManager.GetString("BaseModules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The passage can not be found.
        /// </summary>
        public static string BibleVersePointerCanNotFindPlace {
            get {
                return ResourceManager.GetString("BibleVersePointerCanNotFindPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на String cannot be parsed.
        /// </summary>
        public static string BibleVersePointerCanNotParseString {
            get {
                return ResourceManager.GetString("BibleVersePointerCanNotParseString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Specify the Bible verse.
        /// </summary>
        public static string BibleVersePointerDescription {
            get {
                return ResourceManager.GetString("BibleVersePointerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open a verse.
        /// </summary>
        public static string BibleVersePointerTitle {
            get {
                return ResourceManager.GetString("BibleVersePointerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на books.
        /// </summary>
        public static string Books {
            get {
                return ResourceManager.GetString("Books", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на For the changes to take effect, you must delete and re-add the module with Strong&apos;s Dictionary to the Supplemental Bible..
        /// </summary>
        public static string ChangedNotOneNoteControlsParameter {
            get {
                return ResourceManager.GetString("ChangedNotOneNoteControlsParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This module contains another text of the Bible and other versions of abbreviations of books. For correct program work the follow notebooks must be re-created: Bible, Comments to the Bible, Summary of Notes. Continue?.
        /// </summary>
        public static string ChangeModuleWarning {
            get {
                return ResourceManager.GetString("ChangeModuleWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на OneNote notebooks request fails. Please retry..
        /// </summary>
        public static string ConfiguratorCanNotRequestDataFromOneNote {
            get {
                return ResourceManager.GetString("ConfiguratorCanNotRequestDataFromOneNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Notebook open error.
        /// </summary>
        public static string ConfiguratorErrorWhileNotebookOpenning {
            get {
                return ResourceManager.GetString("ConfiguratorErrorWhileNotebookOpenning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Creating notebook.
        /// </summary>
        public static string ConfiguratorNotebookCreation {
            get {
                return ResourceManager.GetString("ConfiguratorNotebookCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Notebook not defined.
        /// </summary>
        public static string ConfiguratorNotebookNotDefined {
            get {
                return ResourceManager.GetString("ConfiguratorNotebookNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Notebook template not found at.
        /// </summary>
        public static string ConfiguratorNotebookTemplateNotFound {
            get {
                return ResourceManager.GetString("ConfiguratorNotebookTemplateNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete all summary of notes and references to them?.
        /// </summary>
        public static string ConfiguratorQuestionDeleteAllNotesPages {
            get {
                return ResourceManager.GetString("ConfiguratorQuestionDeleteAllNotesPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &apos;Summary of Notes&apos; pages use a separate notebook. It is recommended to manually remove the notebook &apos;Summary of Notes&apos; and recreate it from template. Continue?.
        /// </summary>
        public static string ConfiguratorQuestionDeleteAllNotesPagesManually {
            get {
                return ResourceManager.GetString("ConfiguratorQuestionDeleteAllNotesPagesManually", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Section group not found.
        /// </summary>
        public static string ConfiguratorSectionGroupNotFound {
            get {
                return ResourceManager.GetString("ConfiguratorSectionGroupNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unable to create the notebook. Select a different folder..
        /// </summary>
        public static string ConfiguratorSelectAnotherFolder {
            get {
                return ResourceManager.GetString("ConfiguratorSelectAnotherFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Specify notebook location.
        /// </summary>
        public static string ConfiguratorSetNotebookFolder {
            get {
                return ResourceManager.GetString("ConfiguratorSetNotebookFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Wrong notebook specified &apos;{0}&apos; for type &apos;{1}&apos;..
        /// </summary>
        public static string ConfiguratorWrongNotebookSelected {
            get {
                return ResourceManager.GetString("ConfiguratorWrongNotebookSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Wrong parameter value.
        /// </summary>
        public static string ConfiguratorWrongParameterValue {
            get {
                return ResourceManager.GetString("ConfiguratorWrongParameterValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Creating Supplemental Bible.
        /// </summary>
        public static string CreateSupplementalBible {
            get {
                return ResourceManager.GetString("CreateSupplementalBible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Supplemental Bible was created successfully.
        /// </summary>
        public static string CreateSupplementalBibleFinish {
            get {
                return ResourceManager.GetString("CreateSupplementalBibleFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Creating Supplemental Bible start.
        /// </summary>
        public static string CreateSupplementalBibleStart {
            get {
                return ResourceManager.GetString("CreateSupplementalBibleStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Current Module is undefined..
        /// </summary>
        public static string CurrentModuleIsUndefined {
            get {
                return ResourceManager.GetString("CurrentModuleIsUndefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Notes.
        /// </summary>
        public static string DefaultPageName_Notes {
            get {
                return ResourceManager.GetString("DefaultPageName_Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Detailed notes.
        /// </summary>
        public static string DefaultPageName_RubbishNotes {
            get {
                return ResourceManager.GetString("DefaultPageName_RubbishNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Overview.
        /// </summary>
        public static string DefaultPageNameDefaultBookOverview {
            get {
                return ResourceManager.GetString("DefaultPageNameDefaultBookOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Comments.
        /// </summary>
        public static string DefaultPageNameDefaultComments {
            get {
                return ResourceManager.GetString("DefaultPageNameDefaultComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SB.
        /// </summary>
        public static string DefaultSupplementalBibleLinkName {
            get {
                return ResourceManager.GetString("DefaultSupplementalBibleLinkName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Specify notebook folder.
        /// </summary>
        public static string DefineNotebookDirectory {
            get {
                return ResourceManager.GetString("DefineNotebookDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Close the Dictionaries Notebook?.
        /// </summary>
        public static string DeleteDictionariesNotebookQuestion {
            get {
                return ResourceManager.GetString("DeleteDictionariesNotebookQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &apos;Summary of Notes&apos; pages deleting completed successfully..
        /// </summary>
        public static string DeleteNotesPagesManagerFinishMessage {
            get {
                return ResourceManager.GetString("DeleteNotesPagesManagerFinishMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Page deleting.
        /// </summary>
        public static string DeleteNotesPagesManagerRemovePage {
            get {
                return ResourceManager.GetString("DeleteNotesPagesManagerRemovePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &apos;Summary of Notes&apos; pages deleting start..
        /// </summary>
        public static string DeleteNotesPagesManagerStartMessage {
            get {
                return ResourceManager.GetString("DeleteNotesPagesManagerStartMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Close the Supplemental Bible Notebook?.
        /// </summary>
        public static string DeleteSupplementalBibleQuestion {
            get {
                return ResourceManager.GetString("DeleteSupplementalBibleQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Remove this module.
        /// </summary>
        public static string DeleteThisModule {
            get {
                return ResourceManager.GetString("DeleteThisModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Remove this module from Dictionaries Notebook?.
        /// </summary>
        public static string DeleteThisModuleFromDictionariesNotebookQuestion {
            get {
                return ResourceManager.GetString("DeleteThisModuleFromDictionariesNotebookQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Remove this module from Supplemental Bible Notebook?.
        /// </summary>
        public static string DeleteThisModuleFromSupplementalBibleQuestion {
            get {
                return ResourceManager.GetString("DeleteThisModuleFromSupplementalBibleQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Remove this module?.
        /// </summary>
        public static string DeleteThisModuleQuestion {
            get {
                return ResourceManager.GetString("DeleteThisModuleQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Dictionaries Management.
        /// </summary>
        public static string DictionariesManagement {
            get {
                return ResourceManager.GetString("DictionariesManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Dictionaries.
        /// </summary>
        public static string DictionariesNotebookName {
            get {
                return ResourceManager.GetString("DictionariesNotebookName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Dictionaries notebook was successfully added.
        /// </summary>
        public static string DictionariesNotebookWasAdded {
            get {
                return ResourceManager.GetString("DictionariesNotebookWasAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Dictionaries are not installed. Please use Dictionaries Management Form available on Parameters Form to install dictionaries..
        /// </summary>
        public static string DictionariesNotInstalled {
            get {
                return ResourceManager.GetString("DictionariesNotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Notebook &quot;Dictionaries&quot; cannot be closed if Strong dictionary is installed. First delete module with Strong dictionary from Supplemental Bible on Supplemental Bible management form..
        /// </summary>
        public static string DictionaryNotebookCannotBeClosed {
            get {
                return ResourceManager.GetString("DictionaryNotebookCannotBeClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на http://IStudyBibleTools.com/download.htm?fromProgram=true.
        /// </summary>
        public static string DownloadPageUrl {
            get {
                return ResourceManager.GetString("DownloadPageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Can not find a hierarchy of type &apos;{0}&apos; for element &apos;{1}&apos; {2}.
        /// </summary>
        public static string Error_CanNotFindHierarchy {
            get {
                return ResourceManager.GetString("Error_CanNotFindHierarchy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid module:.
        /// </summary>
        public static string Error_InvalidModule {
            get {
                return ResourceManager.GetString("Error_InvalidModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Notebook template not specified for type &apos;{0}&apos;..
        /// </summary>
        public static string Error_NotebookTemplateNotDefined {
            get {
                return ResourceManager.GetString("Error_NotebookTemplateNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Notebook template not found: &apos;{0}&apos; of type &apos;{1}&apos;..
        /// </summary>
        public static string Error_NotebookTemplateNotFound {
            get {
                return ResourceManager.GetString("Error_NotebookTemplateNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Opened notebook not found.
        /// </summary>
        public static string Error_OpenedNotebookNotFound {
            get {
                return ResourceManager.GetString("Error_OpenedNotebookNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Opened notes page not found.
        /// </summary>
        public static string Error_OpenedNotePageNotFound {
            get {
                return ResourceManager.GetString("Error_OpenedNotePageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Section file not found: &apos;{0}&apos;..
        /// </summary>
        public static string Error_SectionFileNotFound {
            get {
                return ResourceManager.GetString("Error_SectionFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Section group of type &apos;{0}&apos; not specified in notebook template of type &apos;{1}&apos;..
        /// </summary>
        public static string Error_SectionGroupNotDefined {
            get {
                return ResourceManager.GetString("Error_SectionGroupNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The program is not configured. Open the &apos;Program parameters&apos; and specify the necessary settings..
        /// </summary>
        public static string Error_SystemIsNotConfigures {
            get {
                return ResourceManager.GetString("Error_SystemIsNotConfigures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unable to update the page. Perhaps on the page there are painted with a brush elements, which are currently not supported. \nDelete  this elements and try again..
        /// </summary>
        public static string Error_UpdateError_InksOnPages {
            get {
                return ResourceManager.GetString("Error_UpdateError_InksOnPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Update page error.
        /// </summary>
        public static string Error_UpdatePage {
            get {
                return ResourceManager.GetString("Error_UpdatePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error occurred.
        /// </summary>
        public static string ErrorOccurred {
            get {
                return ResourceManager.GetString("ErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ERROR.
        /// </summary>
        public static string ErrorUpper {
            get {
                return ResourceManager.GetString("ErrorUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error while page &apos;{0}&apos; processing.
        /// </summary>
        public static string ErrorWhilePageProcessing {
            get {
                return ResourceManager.GetString("ErrorWhilePageProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File &apos;{0}&apos; not found..
        /// </summary>
        public static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Successfully completed..
        /// </summary>
        public static string FinishSuccessfully {
            get {
                return ResourceManager.GetString("FinishSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Completed with errors..
        /// </summary>
        public static string FinishWithErrors {
            get {
                return ResourceManager.GetString("FinishWithErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Found in one dictionary.
        /// </summary>
        public static string FoundInOneDictionary {
            get {
                return ResourceManager.GetString("FoundInOneDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Found in several dictionaries.
        /// </summary>
        public static string FoundInSeveralDictionaries {
            get {
                return ResourceManager.GetString("FoundInSeveralDictionaries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Indexing Bible.
        /// </summary>
        public static string IndexBible {
            get {
                return ResourceManager.GetString("IndexBible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bible was indexed successfully..
        /// </summary>
        public static string IndexBibleFinish {
            get {
                return ResourceManager.GetString("IndexBibleFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на It is recommended to index the Bible for performance optimization. This operation takes about 30 minutes. Start indexing the Bible now?.
        /// </summary>
        public static string IndexBibleQuestion {
            get {
                return ResourceManager.GetString("IndexBibleQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The Bible is not indexed. It is recommended to index the Bible for performance optimization. This operation takes about 30 minutes. Start indexing the Bible now?.
        /// </summary>
        public static string IndexBibleQuestionAtStartUp {
            get {
                return ResourceManager.GetString("IndexBibleQuestionAtStartUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Indexing Bible start.
        /// </summary>
        public static string IndexBibleStart {
            get {
                return ResourceManager.GetString("IndexBibleStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Indexing Dictionary.
        /// </summary>
        public static string IndexDictionary {
            get {
                return ResourceManager.GetString("IndexDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Indexing Dictionary start.
        /// </summary>
        public static string IndexDictionaryStart {
            get {
                return ResourceManager.GetString("IndexDictionaryStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Indexing Strong Dictionary.
        /// </summary>
        public static string IndexStrongDictionary {
            get {
                return ResourceManager.GetString("IndexStrongDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Indexing Strong Dictionary start.
        /// </summary>
        public static string IndexStrongDictionaryStart {
            get {
                return ResourceManager.GetString("IndexStrongDictionaryStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Linking Supplemental Bible.
        /// </summary>
        public static string LinkSupplementalBible {
            get {
                return ResourceManager.GetString("LinkSupplementalBible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Supplimental Bible was linked successfully.
        /// </summary>
        public static string LinkSupplementalBibleFinish {
            get {
                return ResourceManager.GetString("LinkSupplementalBibleFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Linking Supplemental Bible start.
        /// </summary>
        public static string LinkSupplementalBibleStart {
            get {
                return ResourceManager.GetString("LinkSupplementalBibleStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на To upload the module, use the tab &quot;Modules&quot; of the running application..
        /// </summary>
        public static string LoadMofuleInExistingInstance {
            get {
                return ResourceManager.GetString("LoadMofuleInExistingInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This module can not be deleted because it is used in &quot;Dictionaries&quot; notebook..
        /// </summary>
        public static string ModuleCannotBeDeleted_DictionaryModule {
            get {
                return ResourceManager.GetString("ModuleCannotBeDeleted_DictionaryModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This module can not be deleted because it is used in &quot;Supplemental Bible&quot; notebook..
        /// </summary>
        public static string ModuleCannotBeDeleted_SupplementalBibleModule {
            get {
                return ResourceManager.GetString("ModuleCannotBeDeleted_SupplementalBibleModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Display Name.
        /// </summary>
        public static string ModuleDisplayName {
            get {
                return ResourceManager.GetString("ModuleDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Information about the module.
        /// </summary>
        public static string ModuleInformation {
            get {
                return ResourceManager.GetString("ModuleInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Is Active.
        /// </summary>
        public static string ModuleIsActive {
            get {
                return ResourceManager.GetString("ModuleIsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Module &apos;{0}&apos; is not installed. Please install this module and try again..
        /// </summary>
        public static string ModuleIsNotInstalled {
            get {
                return ResourceManager.GetString("ModuleIsNotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Version of this module is not supported. You should upgrade the program up to version &apos;{0}&apos;. The current version of the program is &apos;{1}&apos;..
        /// </summary>
        public static string ModuleIsNotSupported {
            get {
                return ResourceManager.GetString("ModuleIsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Module uploaded successfully.
        /// </summary>
        public static string ModuleSuccessfullyUploaded {
            get {
                return ResourceManager.GetString("ModuleSuccessfullyUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error on module &apos;{0}&apos; loading: {1}.
        /// </summary>
        public static string ModuleUploadError {
            get {
                return ResourceManager.GetString("ModuleUploadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Version.
        /// </summary>
        public static string ModuleVersion {
            get {
                return ResourceManager.GetString("ModuleVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The module with the same name already exists. Version of existiong module is {0}. Version of uploading module is {1}. The current module will be replaced. Continue?.
        /// </summary>
        public static string ModuleWithSameNameAlreadyExists {
            get {
                return ResourceManager.GetString("ModuleWithSameNameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Another instance of this program is running..
        /// </summary>
        public static string MoreThanSingleInstanceRun {
            get {
                return ResourceManager.GetString("MoreThanSingleInstanceRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на There is a Bible with Strong&apos;s numbers in this notebook. You need to add a notebook with Strong&apos;s dictionary..
        /// </summary>
        public static string NeedToAddDictionaryNotebookWithStrongsNumber {
            get {
                return ResourceManager.GetString("NeedToAddDictionaryNotebookWithStrongsNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на There is a Strong&apos;s dictionary in this notebook. You need to add a Supplemental Bible notebook with Bible with Strong&apos;s numbers..
        /// </summary>
        public static string NeedToAddSupplementalNotebookWithStrongsNumber {
            get {
                return ResourceManager.GetString("NeedToAddSupplementalNotebookWithStrongsNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на http://IStudyBibleTools.com/ServerVariables.xml.
        /// </summary>
        public static string NewVersionOnServerFileUrl {
            get {
                return ResourceManager.GetString("NewVersionOnServerFileUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The notebook &apos;{0}&apos; is not a Dictionaries notebook..
        /// </summary>
        public static string NotebookIsNotDictionariesNotebook {
            get {
                return ResourceManager.GetString("NotebookIsNotDictionariesNotebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The notebook &apos;{0}&apos; is not a Supplemental Bible notebook..
        /// </summary>
        public static string NotebookIsNotSupplementalBible {
            get {
                return ResourceManager.GetString("NotebookIsNotSupplementalBible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Section group can not be found.
        /// </summary>
        public static string NotebookIteratorCanNotFindSectionGroup {
            get {
                return ResourceManager.GetString("NotebookIteratorCanNotFindSectionGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на OneNote hierarchy updating.
        /// </summary>
        public static string NoteLilnkerHierarchyUpdating {
            get {
                return ResourceManager.GetString("NoteLilnkerHierarchyUpdating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sort pages error.
        /// </summary>
        public static string NoteLinkerErrorWhilePageSorting {
            get {
                return ResourceManager.GetString("NoteLinkerErrorWhilePageSorting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Close the program?.
        /// </summary>
        public static string NoteLinkerFormCaptionOnClosing {
            get {
                return ResourceManager.GetString("NoteLinkerFormCaptionOnClosing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hide details.
        /// </summary>
        public static string NoteLinkerHideDetails {
            get {
                return ResourceManager.GetString("NoteLinkerHideDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Initializing....
        /// </summary>
        public static string NoteLinkerInitialization {
            get {
                return ResourceManager.GetString("NoteLinkerInitialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Updating references to &apos;Summary of Notes&apos; pages.
        /// </summary>
        public static string NoteLinkerLinksToNotesPagesUpdating {
            get {
                return ResourceManager.GetString("NoteLinkerLinksToNotesPagesUpdating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Found.
        /// </summary>
        public static string NoteLinkerManyFound {
            get {
                return ResourceManager.GetString("NoteLinkerManyFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на pages.
        /// </summary>
        public static string NoteLinkerManyPages {
            get {
                return ResourceManager.GetString("NoteLinkerManyPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No elements selected.
        /// </summary>
        public static string NoteLinkerNoElementSelected {
            get {
                return ResourceManager.GetString("NoteLinkerNoElementSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &apos;Summary of Notes&apos; pages updating.
        /// </summary>
        public static string NoteLinkerNotesPagesUpdating {
            get {
                return ResourceManager.GetString("NoteLinkerNotesPagesUpdating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на pages.
        /// </summary>
        public static string NoteLinkerOfManyPages {
            get {
                return ResourceManager.GetString("NoteLinkerOfManyPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Found.
        /// </summary>
        public static string NoteLinkerOneFound {
            get {
                return ResourceManager.GetString("NoteLinkerOneFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на page.
        /// </summary>
        public static string NoteLinkerOnePage {
            get {
                return ResourceManager.GetString("NoteLinkerOnePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на OneNote pages updating.
        /// </summary>
        public static string NoteLinkerPagesUpdating {
            get {
                return ResourceManager.GetString("NoteLinkerPagesUpdating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Processing notebook.
        /// </summary>
        public static string NoteLinkerProcessNotebook {
            get {
                return ResourceManager.GetString("NoteLinkerProcessNotebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на In some cases this can lead to incorrect sorting of &apos;Summary of Notes&apos; pages, which is solved only by removing all the &apos;Summary of Notes&apos; pages. Contniue terminating the program?.
        /// </summary>
        public static string NoteLinkerQuestionOnClosing {
            get {
                return ResourceManager.GetString("NoteLinkerQuestionOnClosing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show details.
        /// </summary>
        public static string NoteLinkerShowDetails {
            get {
                return ResourceManager.GetString("NoteLinkerShowDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Final chapter processing.
        /// </summary>
        public static string NoteLinkManagerChapterProcessing {
            get {
                return ResourceManager.GetString("NoteLinkManagerChapterProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error while processing of the page..
        /// </summary>
        public static string NoteLinkManagerProcessingPageErrors {
            get {
                return ResourceManager.GetString("NoteLinkManagerProcessingPageErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Processing the &apos;Summary of Notes&apos; page.
        /// </summary>
        public static string NoteLinkManagerProcessNotesPage {
            get {
                return ResourceManager.GetString("NoteLinkManagerProcessNotesPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Verse cell not found.
        /// </summary>
        public static string NoteLinkManagerVerseCellNotFound {
            get {
                return ResourceManager.GetString("NoteLinkManagerVerseCellNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Pages count in &apos;{0}&apos; is not as expected: expected min {1}, found {2}..
        /// </summary>
        public static string PagesCountLessThanMin {
            get {
                return ResourceManager.GetString("PagesCountLessThanMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Pages count in &apos;{0}&apos; is not as expected: expected max {1}, found {2}..
        /// </summary>
        public static string PagesCountMoreThanMax {
            get {
                return ResourceManager.GetString("PagesCountMoreThanMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Pages count in &apos;{0}&apos; is not as expected: expected {1}, found {2}..
        /// </summary>
        public static string PagesCountNotEqual {
            get {
                return ResourceManager.GetString("PagesCountNotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Process aborted by user.
        /// </summary>
        public static string ProcessAbortedByUser {
            get {
                return ResourceManager.GetString("ProcessAbortedByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Processing the book.
        /// </summary>
        public static string ProcessBook {
            get {
                return ResourceManager.GetString("ProcessBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Processing chapter.
        /// </summary>
        public static string ProcessChapter {
            get {
                return ResourceManager.GetString("ProcessChapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Current page processing.
        /// </summary>
        public static string ProcessCurrentPage {
            get {
                return ResourceManager.GetString("ProcessCurrentPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Notebook processing.
        /// </summary>
        public static string ProcessNotebook {
            get {
                return ResourceManager.GetString("ProcessNotebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Processing the page.
        /// </summary>
        public static string ProcessPage {
            get {
                return ResourceManager.GetString("ProcessPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Processing the section.
        /// </summary>
        public static string ProcessSection {
            get {
                return ResourceManager.GetString("ProcessSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Processing the section group.
        /// </summary>
        public static string ProcessSectionGroup {
            get {
                return ResourceManager.GetString("ProcessSectionGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Processing the verse.
        /// </summary>
        public static string ProcessVerse {
            get {
                return ResourceManager.GetString("ProcessVerse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на References to Comments to the Bible have been updated..
        /// </summary>
        public static string RelinkBibleCommentsManagerFinishMessage {
            get {
                return ResourceManager.GetString("RelinkBibleCommentsManagerFinishMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Start updating references to the Comments to the Bible..
        /// </summary>
        public static string RelinkBibleCommentsManagerStartMessage {
            get {
                return ResourceManager.GetString("RelinkBibleCommentsManagerStartMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Removing parallel Bible translation start.
        /// </summary>
        public static string RemoveParallelBibleTranslation {
            get {
                return ResourceManager.GetString("RemoveParallelBibleTranslation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Parallel Bible translation was removed successfully.
        /// </summary>
        public static string RemoveParallelBibleTranslationFinishMessage {
            get {
                return ResourceManager.GetString("RemoveParallelBibleTranslationFinishMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Supplemental Bible was closed successfully.
        /// </summary>
        public static string RemoveSupplementalBibleFinishMessage {
            get {
                return ResourceManager.GetString("RemoveSupplementalBibleFinishMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bible pages width have been successfully changed..
        /// </summary>
        public static string ResizeBibleTableManagerFinishMessage {
            get {
                return ResourceManager.GetString("ResizeBibleTableManagerFinishMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Start changing the Bible pages width..
        /// </summary>
        public static string ResizeBibleTableManagerStartMessage {
            get {
                return ResourceManager.GetString("ResizeBibleTableManagerStartMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The query is invalid or Microsoft Search 3.0 or 4.0 is not installed on your computer.
        /// </summary>
        public static string SearchQueryIsInvalid {
            get {
                return ResourceManager.GetString("SearchQueryIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Section group &apos;{0}&apos; not found..
        /// </summary>
        public static string SectionGroupNotFound {
            get {
                return ResourceManager.GetString("SectionGroupNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Section group &apos;{0}&apos; not found in &apos;{1}&apos;..
        /// </summary>
        public static string SectionGroupNotFoundInContainer {
            get {
                return ResourceManager.GetString("SectionGroupNotFoundInContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Section group of type &apos;{0}&apos; not found..
        /// </summary>
        public static string SectionGroupOfTypeNotFound {
            get {
                return ResourceManager.GetString("SectionGroupOfTypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Section groups count in &apos;{0}&apos; is not as expected: expected min {1}, found {2}..
        /// </summary>
        public static string SectionGroupsCountLessThanMin {
            get {
                return ResourceManager.GetString("SectionGroupsCountLessThanMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Section groups count in &apos;{0}&apos; is not as expected: expected max {1}, found {2}..
        /// </summary>
        public static string SectionGroupsCountMoreThanMax {
            get {
                return ResourceManager.GetString("SectionGroupsCountMoreThanMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Section groups count in &apos;{0}&apos; is not as expected: expected {1}, found {2}..
        /// </summary>
        public static string SectionGroupsCountNotEqual {
            get {
                return ResourceManager.GetString("SectionGroupsCountNotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Section &apos;{0}&apos; not found..
        /// </summary>
        public static string SectionNotFound {
            get {
                return ResourceManager.GetString("SectionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Section &apos;{0}&apos; not found in &apos;{1}&apos;..
        /// </summary>
        public static string SectionNotFoundInContainer {
            get {
                return ResourceManager.GetString("SectionNotFoundInContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sections count in &apos;{0}&apos; is not as expected: expected min {1}, found {2}..
        /// </summary>
        public static string SectionsCountLessThanMin {
            get {
                return ResourceManager.GetString("SectionsCountLessThanMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sections count in &apos;{0}&apos; is not as expected: expected max {1}, found {2}..
        /// </summary>
        public static string SectionsCountMoreThanMax {
            get {
                return ResourceManager.GetString("SectionsCountMoreThanMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sections count in &apos;{0}&apos; is not as expected: expected {1}, found {2}..
        /// </summary>
        public static string SectionsCountNotEqual {
            get {
                return ResourceManager.GetString("SectionsCountNotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Specified Notebook is of type &apos;{0}&apos;..
        /// </summary>
        public static string SelectedNotebookForType {
            get {
                return ResourceManager.GetString("SelectedNotebookForType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select file with the extension &apos;{0}&apos;..
        /// </summary>
        public static string SelectFileWithExtension {
            get {
                return ResourceManager.GetString("SelectFileWithExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please select term to search.
        /// </summary>
        public static string SelectWord {
            get {
                return ResourceManager.GetString("SelectWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Locking the Bible stored in SkyDrive is not currently supported. Use another kind of internet storage..
        /// </summary>
        public static string SkyDriveBibleIsNotSupportedForLock {
            get {
                return ResourceManager.GetString("SkyDriveBibleIsNotSupportedForLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Stage.
        /// </summary>
        public static string Stage {
            get {
                return ResourceManager.GetString("Stage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Start time.
        /// </summary>
        public static string StartTime {
            get {
                return ResourceManager.GetString("StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Supplemental Bible Management.
        /// </summary>
        public static string SupplementalBibleManagement {
            get {
                return ResourceManager.GetString("SupplementalBibleManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Supplemental Bible.
        /// </summary>
        public static string SupplementalBibleName {
            get {
                return ResourceManager.GetString("SupplementalBibleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Supplemental Bible notebook was successfully added.
        /// </summary>
        public static string SupplementalNotebookWasAdded {
            get {
                return ResourceManager.GetString("SupplementalNotebookWasAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Supported modules not found. Please add necessary modules to the program..
        /// </summary>
        public static string SupportedModulesNotFound {
            get {
                return ResourceManager.GetString("SupportedModulesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Time spent.
        /// </summary>
        public static string TimeSpent {
            get {
                return ResourceManager.GetString("TimeSpent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Use notebook &quot;Dictionaries&quot;.
        /// </summary>
        public static string UseDictionaries {
            get {
                return ResourceManager.GetString("UseDictionaries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Use notebook &quot;Supplemental Bible&quot;.
        /// </summary>
        public static string UseSupplementalBible {
            get {
                return ResourceManager.GetString("UseSupplementalBible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Use this module.
        /// </summary>
        public static string UseThisModule {
            get {
                return ResourceManager.GetString("UseThisModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на verse.
        /// </summary>
        public static string Verse {
            get {
                return ResourceManager.GetString("Verse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на OneNote not started.
        /// </summary>
        public static string VerseLinkerOneNoteNotStarted {
            get {
                return ResourceManager.GetString("VerseLinkerOneNoteNotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Underlined text cannot be extracted.
        /// </summary>
        public static string VerseLinkerUnderlineTextNotExtracted {
            get {
                return ResourceManager.GetString("VerseLinkerUnderlineTextNotExtracted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Underline text not found.
        /// </summary>
        public static string VerseLinkerUnderlineTextNotFound {
            get {
                return ResourceManager.GetString("VerseLinkerUnderlineTextNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Comments page not found.
        /// </summary>
        public static string VerseLinkManagerCommentPageNotFound {
            get {
                return ResourceManager.GetString("VerseLinkManagerCommentPageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Comments section group not found.
        /// </summary>
        public static string VerseLinkManagerCommentSectionGroupNotFound {
            get {
                return ResourceManager.GetString("VerseLinkManagerCommentSectionGroupNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Comments section not found.
        /// </summary>
        public static string VerseLinkManagerCommentSectionNotFound {
            get {
                return ResourceManager.GetString("VerseLinkManagerCommentSectionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на It most likely that not a Bible page is opened in OneNote..
        /// </summary>
        public static string VerseLinkManagerOpenNotBiblePage {
            get {
                return ResourceManager.GetString("VerseLinkManagerOpenNotBiblePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ; .
        /// </summary>
        public static string VerseLinksDelimiter {
            get {
                return ResourceManager.GetString("VerseLinksDelimiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на link {0}.
        /// </summary>
        public static string VerseLinkTemplate {
            get {
                return ResourceManager.GetString("VerseLinkTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на verses.
        /// </summary>
        public static string Verses {
            get {
                return ResourceManager.GetString("Verses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Warning!.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на http://IStudyBibleTools.com.
        /// </summary>
        public static string WebSiteUrl {
            get {
                return ResourceManager.GetString("WebSiteUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Wrong quantity of section groups. Expected {0}, found {1}..
        /// </summary>
        public static string WrongSectionGroupsCount {
            get {
                return ResourceManager.GetString("WrongSectionGroupsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Wrong quantity of sections in section group &apos;{0}&apos;. Expected {1}, found {2}..
        /// </summary>
        public static string WrongSectionsCountInSectionGroup {
            get {
                return ResourceManager.GetString("WrongSectionsCountInSectionGroup", resourceCulture);
            }
        }
    }
}
