//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BibleCommon.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Constants {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Constants() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BibleCommon.Resources.Constants", typeof(Constants).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Старт создания резервной копии данных.
        /// </summary>
        public static string BackupStartInfo {
            get {
                return ResourceManager.GetString("BackupStartInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заметки.
        /// </summary>
        public static string DefaultPageName_Notes {
            get {
                return ResourceManager.GetString("DefaultPageName_Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подробные заметки.
        /// </summary>
        public static string DefaultPageName_RubbishNotes {
            get {
                return ResourceManager.GetString("DefaultPageName_RubbishNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Общий обзор.
        /// </summary>
        public static string DefaultPageNameDefaultBookOverview {
            get {
                return ResourceManager.GetString("DefaultPageNameDefaultBookOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Комментарии.
        /// </summary>
        public static string DefaultPageNameDefaultComments {
            get {
                return ResourceManager.GetString("DefaultPageNameDefaultComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Программа не сконфигурирована. Откройте &apos;Параметры программы&apos; и укажите все необходимые настройки..
        /// </summary>
        public static string Error_SystemIsNotConfigures {
            get {
                return ResourceManager.GetString("Error_SystemIsNotConfigures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось обновить страницу. Возможно на странице присутствуют нарисованные кистью элементы, которые на текущий момент не поддерживаются программой. \nУдалите такие элементы и повторите операцию..
        /// </summary>
        public static string Error_UpdateError_InksOnPages {
            get {
                return ResourceManager.GetString("Error_UpdateError_InksOnPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Время старта:.
        /// </summary>
        public static string StartTime {
            get {
                return ResourceManager.GetString("StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ; .
        /// </summary>
        public static string VerseLinksDelimiter {
            get {
                return ResourceManager.GetString("VerseLinksDelimiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ссылка {0}.
        /// </summary>
        public static string VerseLinkTemplate {
            get {
                return ResourceManager.GetString("VerseLinkTemplate", resourceCulture);
            }
        }
    }
}
