//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BibleCommon {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string NotebookName_Bible {
            get {
                return ((string)(this["NotebookName_Bible"]));
            }
            set {
                this["NotebookName_Bible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string NotebookName_BibleComments {
            get {
                return ((string)(this["NotebookName_BibleComments"]));
            }
            set {
                this["NotebookName_BibleComments"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string NotebookName_BibleStudy {
            get {
                return ((string)(this["NotebookName_BibleStudy"]));
            }
            set {
                this["NotebookName_BibleStudy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SectionGroupName_Bible {
            get {
                return ((string)(this["SectionGroupName_Bible"]));
            }
            set {
                this["SectionGroupName_Bible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SectionGroupName_BibleComments {
            get {
                return ((string)(this["SectionGroupName_BibleComments"]));
            }
            set {
                this["SectionGroupName_BibleComments"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SectionGroupName_BibleStudy {
            get {
                return ((string)(this["SectionGroupName_BibleStudy"]));
            }
            set {
                this["SectionGroupName_BibleStudy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Комментарии")]
        public string PageName_DefaultDescription {
            get {
                return ((string)(this["PageName_DefaultDescription"]));
            }
            set {
                this["PageName_DefaultDescription"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Общий обзор")]
        public string PageName_DefaultBookOverview {
            get {
                return ((string)(this["PageName_DefaultBookOverview"]));
            }
            set {
                this["PageName_DefaultBookOverview"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Заметки")]
        public string PageName_Notes {
            get {
                return ((string)(this["PageName_Notes"]));
            }
            set {
                this["PageName_Notes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Holy Bible")]
        public string NotebookName_Single {
            get {
                return ((string)(this["NotebookName_Single"]));
            }
            set {
                this["NotebookName_Single"] = value;
            }
        }
    }
}
